### ISSUE TITLE
关于数据中的pos

### ISSUE THREAD

**Issue by lzf00** [tricktreat/locate-and-label#11]
请问pos词性标注是用什么工具做的，直接用jieba可以吗，还是需要用特定的分词工具

**Comment by tricktreat** [comment]
我们提供的数据集用的是spacy工具标注的，其他工具也是可以的。

**Comment by dtt-source** [comment]
您好~想向您请教一下在代码中seed spans 是在哪个位置产生的，产出的seed span 是entity_spans_token么~
