### ISSUE TITLE
请问数据集中的pos.json文件是何含义，自己的数据集如何生成？

### ISSUE THREAD

**Issue by Fossettes** [tricktreat/locate-and-label#13]
请问数据集中的pos.json文件是何含义，自己的数据集如何生成？

**Comment by tricktreat** [comment]
用spacy工具对数据集进行part-of-speech标注，注入到json数据集文件的`pos`字段，然后统计pos标签的频数生成pos.json。

**Comment by Fossettes** [comment]
我是使用用nltk工具生成了pos字段，能否跳过注入阶段，直接使用最终的context.json文件？

**Comment by Fossettes** [comment]
谢谢，明白了！

**Comment by Fossettes** [comment]
请问，频率是test和train_dev加在一起的频率吗?

**Comment by tricktreat** [comment]
> 请问，频率是test和train_dev加在一起的频率吗?

只统计train+dev
