### ISSUE TITLE
您好~我想请教一下span 在经过sigmoid（MLP(hi filter)）之后是怎么过滤的？

### ISSUE THREAD

**Issue by dtt-source** [tricktreat/locate-and-label#15]
在models.py中看到 span 过滤这里使用的softmax --> spn_p = torch.softmax(bin_clf,dim=-1) 
计算后得到这样的tensor([[[0.5178, 0.4822], [0.5336, 0.4664],......
下一行代码是spn_mask = spn_p[:,:,0] < self.spn_filter * spn_p[:,:,1]    #如果左边的数字<右边的数*5 mask为true
1、不太理解pi filter 是怎么应用的，是p>某个数字 则span保留么？
2、不太理解 spn_filter  设置成为5的原因
在读过论文和代码后，这里还是不太理解，希望帮忙讲解一下，十分感谢~

**Comment by tricktreat** [comment]
这里是因为正负样本不平衡，spn_filter用来平衡分类的概率。spn_filter是一个超参数，一般等于负采样率neg_entity_count（负样本：正样本）。

**Comment by dtt-source** [comment]
> 明白了，谢谢~
拜托可以再解释下span是怎么通过spn_p过滤的么~ 🙏

**Comment by tricktreat** [comment]
spn_p是一个二分类概率，如果不考虑spn_filter，那spn_p[:,:,0] < spn_p[:,:,1]表示分类为正的概率大于分类为负的概率，保留。
根据filter的二分类概率spn_p，得到spn_mask，在evaluate的
https://github.com/tricktreat/locate-and-label/blob/0e05376fb0174e7eacf66d3c6443a8f1dcab8d5d/identifier/evaluator.py#L52
会进行过滤。

**Comment by dtt-source** [comment]
好嘞，十分感谢🌹~
