### ISSUE TITLE
About Pubmed-shuffle-win-30.bin

### ISSUE THREAD

**Issue by zlh-source** [tricktreat/locate-and-label#6]
Hello, thank you for your open source code, but the file **Pubmed-shuffle-win-30. bin** cannot be downloaded now, could you please provide a copy?

**Comment by tricktreat** [comment]
Hi, I just tried to download it and the file `bio_nlp_vec.tar.gz` is still available for download in the repository (https://github.com/cambridgeltl/BioNLP-2016), please try again.

**Comment by zlh-source** [comment]
Hello, after I click the link （https://drive.google.com/open?id=0BzMCqpcgEJgiUWs0ZnU0NlFTam8） prompt is as follows.
<img width="559" alt="b28789a092ca9a50bdb504a53debb2f" src="https://user-images.githubusercontent.com/50194803/146922388-c0744e4a-394f-434c-9502-4b0c8f7e863d.png">

**Comment by tricktreat** [comment]
It is not convenient to send by email because the file is rather large. 

Maybe because of the ip address restriction? You can switch the vpn node and try another address. In my case, it is directly accessible and downloadable without applying any access rights.

![image](https://user-images.githubusercontent.com/25740077/146928806-0ddc4884-838a-404e-977b-603846e38ba2.png)

**Comment by zlh-source** [comment]
Sorry, I have confirmed that permission is indeed required to access this file. Do not know if you can trouble through Baidu cloud disk or other cloud disk to share?

**Comment by tricktreat** [comment]
Hi, for your request,

链接：https://pan.baidu.com/s/1W7uHKn9g4cyYn-tba41WHA 
提取码：7vcw

**Comment by zlh-source** [comment]
> Thank you very much for your reply!

**Comment by Fujiaoji** [comment]
hello, I meet the same problem, and the link is not valid, please re-share the link, thanks

**Comment by BetweenIslands** [comment]
> > Thank you very much for your reply!

sorry to bother, but I really want the file you were looking for. The url for Baidu cloud disk is not available now. Can you please sent it again?

**Comment by tricktreat** [comment]
> > > Thank you very much for your reply!
> 
> sorry to bother, but I really want the file you were looking for. The url for Baidu cloud disk is not available now. Can you please sent it again?

Hi, for your request:

Link: https://pan.baidu.com/s/1GylnPEer_rdgk_iIMJBkdg  Password: ji0g

**Comment by BetweenIslands** [comment]
Thank you very much for your quick and efficient reply!

**Comment by santiagoTOP** [comment]
谢谢 @tricktreat
