### ISSUE TITLE
Can you provide the ACE dataset preprocess code?

### ISSUE THREAD

**Issue by SCAUapc** [tricktreat/locate-and-label#7]
Hi~ Your work is wonderful ! And I am trying to do some work on nested-ner, But after I process the ACE dataset, I found that the number of  sentences and the number of entity is not equal to your paper. Can you provide the preprocess code?
Thanks !

**Comment by tricktreat** [comment]
Hi, your email has been answered, please check it.

**Comment by hsy-byte** [comment]
> Hi, your email has been answered, please check it.

您好，您方便也向我提供一下ACE数据集的预处理代码吗，邮箱为752040517@qq.com

**Comment by hsy-byte** [comment]
> Hi~ Your work is wonderful ! And I am trying to do some work on nested-ner, But after I process the ACE dataset, I found that the number of sentences and the number of entity is not equal to your paper. Can you provide the preprocess code? Thanks !

您好，您方便也向我提供一下ACE数据集的预处理代码吗，邮箱为752040517@qq.com

**Comment by Shaun-Wong** [comment]
Hi i need ace preprocess code too, can you provide the preprocess code . email : wangxyxychn@163.com

**Comment by djs1014** [comment]
您好，我对您的方法比较感兴趣，方便提供一下ACE数据集的预处理代码吗，邮箱为634751813@qq.com

**Comment by QianGuYiDi** [comment]
您好，我对您的方法比较感兴趣，方便提供一下ACE数据集的预处理代码吗，邮箱为1744585351@qq.com
